version: "3"
services:
  db:
    image: postgres
    container_name: go_microservice_db
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: go_microservice
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - ./database/postgres/postgres-data:/var/lib/postgresql/data
    networks:
      - microservices
    restart: always

networks:
  microservices:
    driver: bridge